version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "install something"
  build:
    commands:
      - echo "In build"
      - grep -Fq "Congratulations" index.html 
  post_build:
    commands:
      - echo "Build completed"